### ISSUE TITLE
Get Committees API Call has duplicate subcommittees

### ISSUE THREAD

**Issue by jden1705** [propublica/congress-api-docs#24]
When calling the get committees endpoint. (https://api.propublica.org/congress/v1/115/house/committees.json) some subcommittees appear multiple times and under incorrect committees. 
Here is what i have found so far, will update if I find more. 

- Energy Subcommittee (ID: HSY20) appearing in foreign affairs committee (incorrect) and Science, Space, and Tech (correct)
- Government Operations (ID: HGO24) appearing in veterans affairs (incorrect) and oversight and government reform (correct)
- Social Security (ID:HWM01) appearing in oversight and government reform (incorrect) and Ways and Means (correct)
- Information Technology (ID: HGO25) appearing in Ways and Means (incorrect) and Oversight and government reform (correct)

Thanks, 
Josh

**Comment by dwillis** [comment]
@jden1705 Thanks for the report - these are fixed now.

**Comment by jden1705** [comment]
@dwillis The energy subcommittee looks good but I'm still seeing the issue with Government Operations, Social security, and Information Technology appearing twice within the get committees call. 
Thanks
