### ISSUE TITLE
House delegates have district 79

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#90]
For example, Guam, American Samoa, and U.S. Virgin Islands.  I would expect blank.

**Comment by konklone** [comment]
Whatever the value of `district`, I would expect `at_large` to be `true` for these delegates. Here's what I see for Guam today:

```
$ curl -s "https://api.propublica.org/congress/v1/members/house/GU/current.json" -H "X-API-Key: [redacted]"
```

```json
{
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "id": "B001245",
         "name": "Madeleine Z. Bordallo",
         "first_name": "Madeleine",
         "middle_name": "Z.",
         "last_name": "Bordallo",
         "role": "Delegate",
         "gender": "F",
         "party": "D",
         "times_topics_url": null,
         "twitter_id": null,
         "facebook_account": null,
         "youtube_id": null,
         "seniority": "16",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/B001245.json",
         "district": "79",
         "at_large": false
      }
]}
```

**Comment by dwillis** [comment]
This should be fixed now.

**Comment by epanchenko** [comment]
At least for Guam, the problem still exists:           {
                 "id": "B001245",
                 "api_uri":"https://api.propublica.org/congress/v1/members/B001245.json",
                 "first_name": "Madeleine",
                 "middle_name": "Z.",
                 "last_name": "Bordallo",
                 "date_of_birth": "1933-05-31",
                 "party": "D",
                 "leadership_role": null,
                 "twitter_account": null,
                 "facebook_account": "madeleine.bordallo",
                 "youtube_account": null,
                 "govtrack_id": "400041",
                 "cspan_id": "1003568",
                 "votesmart_id": "1751",
                 "icpsr_id": "70701",
                 "crp_id": "N00024866",
                 "google_entity_id": "/m/01s_xp",
                 "url": "https://bordallo.house.gov",
                 "rss_url": null,
                 "contact_form": null,
                 "domain": "bordallo.house.gov",
                 "in_office": true,
                 "dw_nominate": null,
                 "ideal_point": null,
                 "seniority": "16",
                 "next_election": "2018",
                 "total_votes": 0,
                 "missed_votes": null,
                 "total_present": null,
                 "ocd_id": "ocd-division/country:us/state:gu/cd:79",
                 "office": null,
                 "phone": null,
                 "fax": null,
                 "state": "GU",
                 "district": "79",
                 "at_large": true,
                 "geoid": "6698"
                 
               },

**Comment by dwillis** [comment]
Just ran this now and I don't see that - is this a caching issue on your end?

**Comment by epanchenko** [comment]
No, I just ran this url again right now and district 79 is still there: https://api.propublica.org/congress/v1/115/house/members.json

**Comment by dwillis** [comment]
Oh, sorry, I was looking at the Current Members response. Will fix this.

**Comment by dwillis** [comment]
Alright, check now.

**Comment by epanchenko** [comment]
Ok now I see At-Large.  Thanks.

**Comment by stevengharris** [comment]
FYI, this change to "At-Large" rather than "0", which was what I was seeing before in the case of, say Wyoming, broke my app. It was my own stupid downstream bug that assumed it was a number, and I'm updating the app. So no worries, but thought you'd like to know.
